package gestionordenadores.vista;

/**
 *
 * @author Robert G
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOper = new javax.swing.ButtonGroup();
        txtDniCli1 = new javax.swing.JTextField();
        lblUsuariio = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JTabbedPane();
        PanelOperarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdOper = new javax.swing.JTextField();
        txtNombreOper = new javax.swing.JTextField();
        txtApellidosOper = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOper = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblImagenOper = new javax.swing.JLabel();
        jRAltasOper = new javax.swing.JRadioButton();
        jRBajasOper = new javax.swing.JRadioButton();
        jRModifOper = new javax.swing.JRadioButton();
        btnOpcionesOper = new gestionordenadores.vista.mycustombutton();
        PanelClientes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDniCli = new javax.swing.JTextField();
        txtNombreCli = new javax.swing.JTextField();
        txtApellidosCli = new javax.swing.JTextField();
        txtDireccCli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCodPostCli = new javax.swing.JTextField();
        txtPoblaCli = new javax.swing.JTextField();
        txtProvCli = new javax.swing.JTextField();
        txtTelCli = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCli = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblImagenCli = new javax.swing.JLabel();
        jRAltasCli = new javax.swing.JRadioButton();
        jRBajasCli = new javax.swing.JRadioButton();
        jRModifCli = new javax.swing.JRadioButton();
        btnOpcionesCli = new gestionordenadores.vista.mycustombutton();
        PanelProveedores = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCifPro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCodPostPro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNombrePro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPoblaPro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtDireccPro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtProvPro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTelPro = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePro = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblImagenPro = new javax.swing.JLabel();
        jRAltasPro = new javax.swing.JRadioButton();
        jRBajasPro = new javax.swing.JRadioButton();
        jRModifPro = new javax.swing.JRadioButton();
        btnOpcionesPro = new gestionordenadores.vista.mycustombutton();
        PanelTipos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableTipos = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        txtIdTipo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtTipoCom = new javax.swing.JTextField();
        jRAltasTipo = new javax.swing.JRadioButton();
        jRBajasTipo = new javax.swing.JRadioButton();
        jRModifTipo = new javax.swing.JRadioButton();
        btnOpcionesTipo = new gestionordenadores.vista.mycustombutton();
        jPanel5 = new javax.swing.JPanel();
        lblImagenTipo = new javax.swing.JLabel();
        PanelComponentes = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtIdCom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtPrecioCom = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNombreCom = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCifProCom = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtMarcaCom = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtIdTipoCom = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDescriCom = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtEstadoCom = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCom = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblImagenCom = new javax.swing.JLabel();
        jRAltasCom = new javax.swing.JRadioButton();
        jRBajasCom = new javax.swing.JRadioButton();
        jRModifCom = new javax.swing.JRadioButton();
        btnOpcionesCom = new gestionordenadores.vista.mycustombutton();
        cbNomProv = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        cbNomTip = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txtEstadoCom2 = new javax.swing.JTextField();
        PanelOrdenadores = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        txtIdOrd = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtModeloOrd = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableOrd = new javax.swing.JTable();
        jRAltasOrd = new javax.swing.JRadioButton();
        jRBajasOrd = new javax.swing.JRadioButton();
        jRModifOrd = new javax.swing.JRadioButton();
        btnOpcionesOrd = new gestionordenadores.vista.mycustombutton();
        jPanel6 = new javax.swing.JPanel();
        lblImagenOrd = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtPrecioOrd = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbDniCli = new javax.swing.JComboBox<>();
        fechaMont = new com.toedter.calendar.JDateChooser();
        PanelMontajes = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtMonIdOrd = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtMonIdCom = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtMonIdOper = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableMon = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lblImagenMon = new javax.swing.JLabel();
        txtInfoMon = new javax.swing.JLabel();
        txtNomCliMon = new javax.swing.JTextField();
        txtInfoMon1 = new javax.swing.JLabel();
        txtDniCliMon = new javax.swing.JTextField();
        PanelReparaciones = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        txtRepIdOrd = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtRepIdCom = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtRepIdOper = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableRep = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        lblImagenMon1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        fechaRep = new com.toedter.calendar.JDateChooser();
        jLabel45 = new javax.swing.JLabel();
        txtPrecioRep = new javax.swing.JTextField();
        PanelInformes = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        btnVistaAgrup = new gestionordenadores.vista.mycustombutton();
        btnPdfAgrup = new gestionordenadores.vista.mycustombutton();
        jPanel10 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        btnVistaParam = new gestionordenadores.vista.mycustombutton();
        btnPdfParam = new gestionordenadores.vista.mycustombutton();
        cbParam = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblGestionOrdenadores = new javax.swing.JLabel();
        lblInfosurTecnologia = new javax.swing.JLabel();
        btnDeslog = new gestionordenadores.vista.mycustombutton();
        btnAyuda = new gestionordenadores.vista.mycustombutton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Ordenadores - Principal");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuariio.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        getContentPane().add(lblUsuariio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 99, 27));

        jLabel3.setText("Id:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellidos:");

        jTableOper.setBackground(new java.awt.Color(151, 219, 248));
        jTableOper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOper);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenOper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenOper, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        buttonGroupOper.add(jRAltasOper);
        jRAltasOper.setText("ALTAS");

        buttonGroupOper.add(jRBajasOper);
        jRBajasOper.setText("BAJAS");

        buttonGroupOper.add(jRModifOper);
        jRModifOper.setText("MODIFICACIONES");

        javax.swing.GroupLayout PanelOperariosLayout = new javax.swing.GroupLayout(PanelOperarios);
        PanelOperarios.setLayout(PanelOperariosLayout);
        PanelOperariosLayout.setHorizontalGroup(
            PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOperariosLayout.createSequentialGroup()
                        .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelOperariosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidosOper, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelOperariosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreOper, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdOper, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelOperariosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpcionesOper, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addGroup(PanelOperariosLayout.createSequentialGroup()
                                .addComponent(jRAltasOper)
                                .addGap(18, 18, 18)
                                .addComponent(jRBajasOper)
                                .addGap(18, 18, 18)
                                .addComponent(jRModifOper))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelOperariosLayout.setVerticalGroup(
            PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApellidosOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelOperariosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelOperariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasOper)
                            .addComponent(jRBajasOper)
                            .addComponent(jRModifOper))
                        .addGap(18, 18, 18)
                        .addComponent(btnOpcionesOper, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Operarios", PanelOperarios);

        jLabel6.setText("DNI:");

        jLabel7.setText("Nombre:");

        jLabel8.setText("Apellidos:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("Código Postal:");

        jLabel11.setText("Población:");

        jLabel12.setText("Provincia:");

        jLabel13.setText("Teléfono:");

        jTableCli.setBackground(new java.awt.Color(151, 219, 248));
        jTableCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCli);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(4, 259));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        buttonGroupOper.add(jRAltasCli);
        jRAltasCli.setText("ALTAS");

        buttonGroupOper.add(jRBajasCli);
        jRBajasCli.setText("BAJAS");

        buttonGroupOper.add(jRModifCli);
        jRModifCli.setText("MODIFICACIONES");

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidosCli, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccCli))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPoblaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPostCli, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProvCli, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(118, Short.MAX_VALUE))
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClientesLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelClientesLayout.createSequentialGroup()
                                .addComponent(btnOpcionesCli, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
                            .addGroup(PanelClientesLayout.createSequentialGroup()
                                .addComponent(jRAltasCli)
                                .addGap(18, 18, 18)
                                .addComponent(jRBajasCli)
                                .addGap(18, 18, 18)
                                .addComponent(jRModifCli)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodPostCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombreCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPoblaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApellidosCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtProvCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelClientesLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasCli)
                            .addComponent(jRBajasCli)
                            .addComponent(jRModifCli))
                        .addGap(17, 17, 17)
                        .addComponent(btnOpcionesCli, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Clientes", PanelClientes);

        jLabel14.setText("CIF:");

        jLabel15.setText("Código Postal:");

        jLabel16.setText("Nombre:");

        jLabel17.setText("Población:");

        jLabel18.setText("Dirección:");

        jLabel19.setText("Provincia:");

        jLabel20.setText("Teléfono:");

        jTablePro.setBackground(new java.awt.Color(151, 219, 248));
        jTablePro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePro);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(4, 259));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        buttonGroupOper.add(jRAltasPro);
        jRAltasPro.setText("ALTAS");

        buttonGroupOper.add(jRBajasPro);
        jRBajasPro.setText("BAJAS");

        buttonGroupOper.add(jRModifPro);
        jRModifPro.setText("MODIFICACIONES");

        javax.swing.GroupLayout PanelProveedoresLayout = new javax.swing.GroupLayout(PanelProveedores);
        PanelProveedores.setLayout(PanelProveedoresLayout);
        PanelProveedoresLayout.setHorizontalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCifPro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                                .addComponent(txtDireccPro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPoblaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPostPro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProvPro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118))
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpcionesPro, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                                        .addComponent(jRAltasPro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBajasPro)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRModifPro)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        PanelProveedoresLayout.setVerticalGroup(
            PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCifPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodPostPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtPoblaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtProvPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtDireccPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtTelPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasPro)
                            .addComponent(jRBajasPro)
                            .addComponent(jRModifPro))
                        .addGap(17, 17, 17)
                        .addComponent(btnOpcionesPro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Proveedores", PanelProveedores);

        jTableTipos.setBackground(new java.awt.Color(151, 219, 248));
        jTableTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableTipos);

        jLabel31.setText("Id:");

        jLabel32.setText("Tipo:");

        buttonGroupOper.add(jRAltasTipo);
        jRAltasTipo.setText("ALTAS");

        buttonGroupOper.add(jRBajasTipo);
        jRBajasTipo.setText("BAJAS");

        buttonGroupOper.add(jRModifTipo);
        jRModifTipo.setText("MODIFICACIONES");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagenTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo/tipos.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelTiposLayout = new javax.swing.GroupLayout(PanelTipos);
        PanelTipos.setLayout(PanelTiposLayout);
        PanelTiposLayout.setHorizontalGroup(
            PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTiposLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpcionesTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addGroup(PanelTiposLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(PanelTiposLayout.createSequentialGroup()
                                .addComponent(jRAltasTipo)
                                .addGap(18, 18, 18)
                                .addComponent(jRBajasTipo)
                                .addGap(18, 18, 18)
                                .addComponent(jRModifTipo))))
                    .addGroup(PanelTiposLayout.createSequentialGroup()
                        .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelTiposLayout.setVerticalGroup(
            PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtIdTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtTipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTiposLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelTiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasTipo)
                            .addComponent(jRBajasTipo)
                            .addComponent(jRModifTipo))
                        .addGap(18, 18, 18)
                        .addComponent(btnOpcionesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelPrincipal.addTab("Tipos", PanelTipos);

        jLabel21.setText("Id:");

        jLabel22.setText("Precio:");

        jLabel23.setText("Nombre:");

        jLabel24.setText("Cif Prov:");

        txtCifProCom.setEnabled(false);

        jLabel25.setText("Marca:");

        jLabel26.setText("Id Tipo:");

        txtIdTipoCom.setEnabled(false);

        jLabel27.setText("Descripción:");

        jLabel28.setText("Estado:");

        jTableCom.setBackground(new java.awt.Color(151, 219, 248));
        jTableCom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCom);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 259));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenCom, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenCom, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        buttonGroupOper.add(jRAltasCom);
        jRAltasCom.setText("ALTAS");

        buttonGroupOper.add(jRBajasCom);
        jRBajasCom.setText("BAJAS");

        buttonGroupOper.add(jRModifCom);
        jRModifCom.setText("MODIFICACIONES");

        jLabel29.setText("Elige proveedor en CB");

        jLabel30.setText("Elige componente en CB");

        javax.swing.GroupLayout PanelComponentesLayout = new javax.swing.GroupLayout(PanelComponentes);
        PanelComponentes.setLayout(PanelComponentesLayout);
        PanelComponentesLayout.setHorizontalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOpcionesCom, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addComponent(jRAltasCom)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRBajasCom)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRModifCom))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelComponentesLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(txtDescriCom, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel28))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarcaCom, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtNombreCom))
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24)))))
                        .addGap(18, 18, 18)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdTipoCom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCifProCom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioCom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbNomTip, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)
                                        .addComponent(cbNomProv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(PanelComponentesLayout.createSequentialGroup()
                                .addComponent(txtEstadoCom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstadoCom2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        PanelComponentesLayout.setVerticalGroup(
            PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(txtPrecioCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtNombreCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtCifProCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNomProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtMarcaCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtIdTipoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNomTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel30))
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtDescriCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtEstadoCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoCom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelComponentesLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(PanelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasCom)
                            .addComponent(jRBajasCom)
                            .addComponent(jRModifCom))
                        .addGap(17, 17, 17)
                        .addComponent(btnOpcionesCom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Componentes", PanelComponentes);

        jLabel33.setText("Id:");

        jLabel34.setText("Modelo:");

        jTableOrd.setBackground(new java.awt.Color(151, 219, 248));
        jTableOrd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableOrd);

        buttonGroupOper.add(jRAltasOrd);
        jRAltasOrd.setText("ALTAS");

        buttonGroupOper.add(jRBajasOrd);
        jRBajasOrd.setText("BAJAS");

        buttonGroupOper.add(jRModifOrd);
        jRModifOrd.setText("MODIFICACIONES");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagenOrd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ord/ordenadores.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel35.setText("Precio:");

        jLabel36.setText("DNI Cliente:");

        jLabel37.setText("Fecha Montaje:");

        javax.swing.GroupLayout PanelOrdenadoresLayout = new javax.swing.GroupLayout(PanelOrdenadores);
        PanelOrdenadores.setLayout(PanelOrdenadoresLayout);
        PanelOrdenadoresLayout.setHorizontalGroup(
            PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModeloOrd)
                            .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpcionesOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                        .addComponent(jRAltasOrd)
                        .addGap(18, 18, 18)
                        .addComponent(jRBajasOrd)
                        .addGap(18, 18, 18)
                        .addComponent(jRModifOrd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOrdenadoresLayout.createSequentialGroup()
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbDniCli, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaMont, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGap(19, 19, 19))
        );
        PanelOrdenadoresLayout.setVerticalGroup(
            PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOrdenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtIdOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtModeloOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(cbDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(fechaMont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtPrecioOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelOrdenadoresLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelOrdenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRAltasOrd)
                            .addComponent(jRBajasOrd)
                            .addComponent(jRModifOrd))
                        .addGap(18, 18, 18)
                        .addComponent(btnOpcionesOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelPrincipal.addTab("Ordenadores", PanelOrdenadores);

        jLabel38.setText("Id Ordenador:");

        jLabel39.setText("Id Componente:");

        jLabel40.setText("Id Operario:");

        jTableMon.setBackground(new java.awt.Color(151, 219, 248));
        jTableMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTableMon);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagenMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mon/montajes.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        txtInfoMon.setText("Esta Id pertenece al cliente:");

        txtInfoMon1.setText("Con el siguiente DNI:");

        javax.swing.GroupLayout PanelMontajesLayout = new javax.swing.GroupLayout(PanelMontajes);
        PanelMontajes.setLayout(PanelMontajesLayout);
        PanelMontajesLayout.setHorizontalGroup(
            PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMontajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMontajesLayout.createSequentialGroup()
                        .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMontajesLayout.createSequentialGroup()
                                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelMontajesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMonIdCom, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(txtMonIdOrd)))
                                    .addGroup(PanelMontajesLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMonIdOper))))
                            .addGroup(PanelMontajesLayout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(txtInfoMon)))
                        .addGap(18, 18, 18)
                        .addComponent(txtNomCliMon)))
                .addGap(18, 18, 18)
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMontajesLayout.createSequentialGroup()
                        .addComponent(txtInfoMon1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDniCliMon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMontajesLayout.setVerticalGroup(
            PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMontajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtMonIdOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInfoMon)
                    .addComponent(txtNomCliMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInfoMon1)
                    .addComponent(txtDniCliMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtMonIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtMonIdOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(PanelMontajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelPrincipal.addTab("Montajes", PanelMontajes);

        jLabel41.setText("Id Ordenador:");

        jLabel42.setText("Id Componente:");

        jLabel43.setText("Id Operario:");

        jTableRep.setBackground(new java.awt.Color(151, 219, 248));
        jTableRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTableRep);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagenMon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rep/reparaciones.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenMon1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenMon1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        jLabel44.setText("Fecha Reparación:");

        jLabel45.setText("Precio:");

        javax.swing.GroupLayout PanelReparacionesLayout = new javax.swing.GroupLayout(PanelReparaciones);
        PanelReparaciones.setLayout(PanelReparacionesLayout);
        PanelReparacionesLayout.setHorizontalGroup(
            PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReparacionesLayout.createSequentialGroup()
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRepIdCom)
                                    .addComponent(txtRepIdOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtRepIdOper, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaRep, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtPrecioRep))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelReparacionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelReparacionesLayout.setVerticalGroup(
            PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelReparacionesLayout.createSequentialGroup()
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtRepIdOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(18, 18, 18)
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtRepIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addGap(18, 18, 18)
                        .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txtRepIdOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelReparacionesLayout.createSequentialGroup()
                        .addComponent(fechaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Reparaciones", PanelReparaciones);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(151, 219, 248));
        jLabel46.setText("Listado de componentes agrupados por tipo:");

        btnVistaAgrup.setText("Vista Previa");

        btnPdfAgrup.setText("Guardar en PDF");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVistaAgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPdfAgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(btnVistaAgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdfAgrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(151, 219, 248));
        jLabel47.setText("Listado de componentes parametrizados por marca:");

        btnVistaParam.setText("Vista Previa");

        btnPdfParam.setText("Guardar en PDF");

        cbParam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbParam.setForeground(new java.awt.Color(0, 109, 151));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(cbParam, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVistaParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPdfParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVistaParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPdfParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbParam))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelInformesLayout = new javax.swing.GroupLayout(PanelInformes);
        PanelInformes.setLayout(PanelInformesLayout);
        PanelInformesLayout.setHorizontalGroup(
            PanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInformesLayout.setVerticalGroup(
            PanelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        PanelPrincipal.addTab("Informes", PanelInformes);

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 790, 550));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 60, 27));

        lblGestionOrdenadores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblGestionOrdenadores.setForeground(new java.awt.Color(0, 109, 151));
        lblGestionOrdenadores.setText("GESTIÓN ORDENADORES");
        getContentPane().add(lblGestionOrdenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 280, -1));

        lblInfosurTecnologia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblInfosurTecnologia.setForeground(new java.awt.Color(0, 109, 151));
        lblInfosurTecnologia.setText("INFOSUR TECNOLOGÍA");
        getContentPane().add(lblInfosurTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 230, -1));

        btnDeslog.setText("Desloguear");
        btnDeslog.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        getContentPane().add(btnDeslog, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        btnAyuda.setText("Ayuda");
        getContentPane().add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_principal.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PanelClientes;
    public javax.swing.JPanel PanelComponentes;
    public javax.swing.JPanel PanelInformes;
    public javax.swing.JPanel PanelMontajes;
    public javax.swing.JPanel PanelOperarios;
    public javax.swing.JPanel PanelOrdenadores;
    public javax.swing.JTabbedPane PanelPrincipal;
    public javax.swing.JPanel PanelProveedores;
    public javax.swing.JPanel PanelReparaciones;
    public javax.swing.JPanel PanelTipos;
    public gestionordenadores.vista.mycustombutton btnAyuda;
    public gestionordenadores.vista.mycustombutton btnDeslog;
    public gestionordenadores.vista.mycustombutton btnOpcionesCli;
    public gestionordenadores.vista.mycustombutton btnOpcionesCom;
    public gestionordenadores.vista.mycustombutton btnOpcionesOper;
    public gestionordenadores.vista.mycustombutton btnOpcionesOrd;
    public gestionordenadores.vista.mycustombutton btnOpcionesPro;
    public gestionordenadores.vista.mycustombutton btnOpcionesTipo;
    public gestionordenadores.vista.mycustombutton btnPdfAgrup;
    public gestionordenadores.vista.mycustombutton btnPdfParam;
    public gestionordenadores.vista.mycustombutton btnVistaAgrup;
    public gestionordenadores.vista.mycustombutton btnVistaParam;
    private javax.swing.ButtonGroup buttonGroupOper;
    public javax.swing.JComboBox<String> cbDniCli;
    public javax.swing.JComboBox<String> cbNomProv;
    public javax.swing.JComboBox<String> cbNomTip;
    public javax.swing.JComboBox<String> cbParam;
    public com.toedter.calendar.JDateChooser fechaMont;
    public com.toedter.calendar.JDateChooser fechaRep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JRadioButton jRAltasCli;
    public javax.swing.JRadioButton jRAltasCom;
    public javax.swing.JRadioButton jRAltasOper;
    public javax.swing.JRadioButton jRAltasOrd;
    public javax.swing.JRadioButton jRAltasPro;
    public javax.swing.JRadioButton jRAltasTipo;
    public javax.swing.JRadioButton jRBajasCli;
    public javax.swing.JRadioButton jRBajasCom;
    public javax.swing.JRadioButton jRBajasOper;
    public javax.swing.JRadioButton jRBajasOrd;
    public javax.swing.JRadioButton jRBajasPro;
    public javax.swing.JRadioButton jRBajasTipo;
    public javax.swing.JRadioButton jRModifCli;
    public javax.swing.JRadioButton jRModifCom;
    public javax.swing.JRadioButton jRModifOper;
    public javax.swing.JRadioButton jRModifOrd;
    public javax.swing.JRadioButton jRModifPro;
    public javax.swing.JRadioButton jRModifTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JTable jTableCli;
    public javax.swing.JTable jTableCom;
    public javax.swing.JTable jTableMon;
    public javax.swing.JTable jTableOper;
    public javax.swing.JTable jTableOrd;
    public javax.swing.JTable jTablePro;
    public javax.swing.JTable jTableRep;
    public javax.swing.JTable jTableTipos;
    private javax.swing.JLabel lblGestionOrdenadores;
    public javax.swing.JLabel lblImagenCli;
    public javax.swing.JLabel lblImagenCom;
    public javax.swing.JLabel lblImagenMon;
    public javax.swing.JLabel lblImagenMon1;
    public javax.swing.JLabel lblImagenOper;
    public javax.swing.JLabel lblImagenOrd;
    public javax.swing.JLabel lblImagenPro;
    public javax.swing.JLabel lblImagenTipo;
    private javax.swing.JLabel lblInfosurTecnologia;
    public javax.swing.JLabel lblUsuariio;
    public javax.swing.JTextField txtApellidosCli;
    public javax.swing.JTextField txtApellidosOper;
    public javax.swing.JTextField txtCifPro;
    public javax.swing.JTextField txtCifProCom;
    public javax.swing.JTextField txtCodPostCli;
    public javax.swing.JTextField txtCodPostPro;
    public javax.swing.JTextField txtDescriCom;
    public javax.swing.JTextField txtDireccCli;
    public javax.swing.JTextField txtDireccPro;
    public javax.swing.JTextField txtDniCli;
    public javax.swing.JTextField txtDniCli1;
    public javax.swing.JTextField txtDniCliMon;
    public javax.swing.JTextField txtEstadoCom;
    public javax.swing.JTextField txtEstadoCom2;
    public javax.swing.JTextField txtIdCom;
    public javax.swing.JTextField txtIdOper;
    public javax.swing.JTextField txtIdOrd;
    public javax.swing.JTextField txtIdTipo;
    public javax.swing.JTextField txtIdTipoCom;
    private javax.swing.JLabel txtInfoMon;
    private javax.swing.JLabel txtInfoMon1;
    public javax.swing.JTextField txtMarcaCom;
    public javax.swing.JTextField txtModeloOrd;
    public javax.swing.JTextField txtMonIdCom;
    public javax.swing.JTextField txtMonIdOper;
    public javax.swing.JTextField txtMonIdOrd;
    public javax.swing.JTextField txtNomCliMon;
    public javax.swing.JTextField txtNombreCli;
    public javax.swing.JTextField txtNombreCom;
    public javax.swing.JTextField txtNombreOper;
    public javax.swing.JTextField txtNombrePro;
    public javax.swing.JTextField txtPoblaCli;
    public javax.swing.JTextField txtPoblaPro;
    public javax.swing.JTextField txtPrecioCom;
    public javax.swing.JTextField txtPrecioOrd;
    public javax.swing.JTextField txtPrecioRep;
    public javax.swing.JTextField txtProvCli;
    public javax.swing.JTextField txtProvPro;
    public javax.swing.JTextField txtRepIdCom;
    public javax.swing.JTextField txtRepIdOper;
    public javax.swing.JTextField txtRepIdOrd;
    public javax.swing.JTextField txtTelCli;
    public javax.swing.JTextField txtTelPro;
    public javax.swing.JTextField txtTipoCom;
    // End of variables declaration//GEN-END:variables
}
