/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionordenadores.vista;

/**
 *
 * @author Usuario
 */
public class VistaAyuda extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form VistaAyuda
     */
    public VistaAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAyudaOper = new javax.swing.JButton();
        btnAyudaCli = new javax.swing.JButton();
        lblGestionOrdenadores = new javax.swing.JLabel();
        lblInfosurTecnologia = new javax.swing.JLabel();
        btnAyudaPro = new javax.swing.JButton();
        btnAyudaTip = new javax.swing.JButton();
        btnAyudaCom = new javax.swing.JButton();
        btnAyudaOrd = new javax.swing.JButton();
        btnAyudaMon = new javax.swing.JButton();
        btnAyudaRep = new javax.swing.JButton();
        btnAyudaInf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiAyuda = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAyudaOper.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaOper.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaOper.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaOper.setText("Operarios");
        getContentPane().add(btnAyudaOper, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnAyudaCli.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaCli.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaCli.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaCli.setText("Clientes");
        getContentPane().add(btnAyudaCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        lblGestionOrdenadores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblGestionOrdenadores.setForeground(new java.awt.Color(0, 109, 151));
        lblGestionOrdenadores.setText("GESTIÓN ORDENADORES");
        getContentPane().add(lblGestionOrdenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, -1));

        lblInfosurTecnologia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblInfosurTecnologia.setForeground(new java.awt.Color(0, 109, 151));
        lblInfosurTecnologia.setText("INFOSUR TECNOLOGÍA");
        getContentPane().add(lblInfosurTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        btnAyudaPro.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaPro.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaPro.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaPro.setText("Proveedores");
        getContentPane().add(btnAyudaPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        btnAyudaTip.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaTip.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaTip.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaTip.setText("Tipos");
        getContentPane().add(btnAyudaTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        btnAyudaCom.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaCom.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaCom.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaCom.setText("Componentes");
        getContentPane().add(btnAyudaCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        btnAyudaOrd.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaOrd.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaOrd.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaOrd.setText("Ordenadores");
        getContentPane().add(btnAyudaOrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        btnAyudaMon.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaMon.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaMon.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaMon.setText("Montajes");
        getContentPane().add(btnAyudaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        btnAyudaRep.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaRep.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaRep.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaRep.setText("Reparaciones");
        getContentPane().add(btnAyudaRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        btnAyudaInf.setBackground(new java.awt.Color(255, 204, 204));
        btnAyudaInf.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnAyudaInf.setForeground(new java.awt.Color(204, 0, 0));
        btnAyudaInf.setText("Informes");
        getContentPane().add(btnAyudaInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ayuda.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 420));

        jMenu2.setText("Ayuda");

        jmiAyuda.setText("F1");
        jMenu2.add(jmiAyuda);

        btnSalir.setText("Salir");
        jMenu2.add(btnSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAyudaCli;
    public javax.swing.JButton btnAyudaCom;
    public javax.swing.JButton btnAyudaInf;
    public javax.swing.JButton btnAyudaMon;
    public javax.swing.JButton btnAyudaOper;
    public javax.swing.JButton btnAyudaOrd;
    public javax.swing.JButton btnAyudaPro;
    public javax.swing.JButton btnAyudaRep;
    public javax.swing.JButton btnAyudaTip;
    public javax.swing.JMenuItem btnSalir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JLabel lblGestionOrdenadores;
    private javax.swing.JLabel lblInfosurTecnologia;
    // End of variables declaration//GEN-END:variables
}
