/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionordenadores.vista;


/**
 *
 * @author Rober3
 */
public class VistaUsuarios extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form VistaUsuarios
     */
    public VistaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblGestionOrdenadores = new javax.swing.JLabel();
        lblInfosurTecnologia = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnEntrar = new gestionordenadores.vista.mycustombutton();
        btnSalir = new gestionordenadores.vista.mycustombutton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar_usuarios.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 160, 150));

        lblGestionOrdenadores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblGestionOrdenadores.setForeground(new java.awt.Color(0, 109, 151));
        lblGestionOrdenadores.setText("GESTIÓN ORDENADORES");
        getContentPane().add(lblGestionOrdenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, -1));

        lblInfosurTecnologia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblInfosurTecnologia.setForeground(new java.awt.Color(0, 109, 151));
        lblInfosurTecnologia.setText("INFOSUR TECNOLOGÍA");
        getContentPane().add(lblInfosurTecnologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 30));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(151, 219, 248));
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 20));

        lblContrasena.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(151, 219, 248));
        lblContrasena.setText("Contraseña:");
        getContentPane().add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 130, -1));

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 120, 30));

        btnEntrar.setText("ENTRAR");
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        btnSalir.setText("SALIR");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_usuarios.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public gestionordenadores.vista.mycustombutton btnEntrar;
    public gestionordenadores.vista.mycustombutton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblGestionOrdenadores;
    private javax.swing.JLabel lblInfosurTecnologia;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField txtPassword;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
